[package]
name = "hangman"
version = "0.1.0"
authors = ["Caleb Webber <caleb@codingthemsoftly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
env_logger = "*"
envconfig = "0.9.1"
